global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # FastVLM application metrics
  - job_name: 'fastvm-app'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    
  # FastVLM model converter service
  - job_name: 'fastvm-converter'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: /converter/metrics
    scrape_interval: 60s  # Conversion is slower operation
    scrape_timeout: 30s
    
  # System metrics via node_exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Redis metrics (for job queue)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s
    
  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 30s
    
  # Pushgateway for batch jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']
    scrape_interval: 30s
    honor_labels: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 10GB