name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - Model Conversion (Python)
        - iOS/Swift Integration
        - Performance Optimization
        - New Model Architecture
        - Developer Tools
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "Describe the problem or use case this feature would address"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "Describe how you envision this feature working"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Describe any alternative approaches you've considered"

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: "Share any thoughts on implementation approach"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (important for my use case)
        - Critical (blocking my use case)

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples showing how this feature would be used
      render: python
      placeholder: |
        # Example usage
        converter = FastVLMConverter()
        # Your proposed feature usage here

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: Python (model conversion)
        - label: iOS (Swift)
        - label: macOS (Swift)
        - label: All platforms

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Any additional information that would be helpful"

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be willing to contribute to implementing this feature
        - label: I would be willing to help with testing this feature
        - label: I would be willing to help with documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature request is specific and actionable
          required: true
        - label: I have provided sufficient detail and context
          required: true