version: '3.8'

services:
  converter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.converter
      target: development
    volumes:
      - ../src:/workspace/src:ro
      - ../tests:/workspace/tests:ro
      - model-cache:/workspace/models
      - ./checkpoints:/workspace/checkpoints
    environment:
      - PYTHONPATH=/workspace/src
      - MLCOMPUTE_AVAILABLE_DEVICES=cpu
    ports:
      - "8000:8000"
    command: ["python", "-m", "pytest", "-v"]

  benchmark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.converter
      target: production
    volumes:
      - model-cache:/workspace/models
      - ./benchmarks:/workspace/benchmarks
    environment:
      - BENCHMARK_ITERATIONS=100
    command: ["python", "-m", "fast_vlm_ondevice.benchmark"]

  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.converter
      target: development
    volumes:
      - ../:/workspace
      - model-cache:/workspace/models
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

volumes:
  model-cache:
    driver: local

networks:
  default:
    name: fastvlm-network